### ISSUE TITLE
URL's with trailing slash vs. no trailing slash are considered equal

### ISSUE THREAD

**Issue by mpelzsherman** [rentpath/duke_of_url#1]
This is due to the way postrank works.

https://github.com/postrank-labs/postrank-uri/issues/4

One of the SEO tests we perform is to confirm that requests without a trailing slash redirect to the same URL with a slash.

We might be able to work around this but I thought I'd document this issue here.

**Comment by martinstreicher** [comment]
Hmmm... I wonder if this an issue. The job of Duke is to normalize URLs. A trailing slash would be removed intentionally to make the URL conform to the normal form. In the universe, is a trailing slash relevant?

**Comment by martinstreicher** [comment]
@mpelzsherman This is an *old* issue. Is it still relevant?

**Comment by martinstreicher** [comment]
I am going to close this. MPS if it is still something we should worry about reopen with comment.
